### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by huajideshutiao** [kagg886/Pixiv-MultiPlatform#1]
夜间模式(比较需要)
用户详情页的个人简介栏移动到最后(确实没啥用)
允许关闭检查更新(或者无更新时隐藏toast)
多个图片折叠(比如124061838，有很多图，有时候看第一张图就想收藏，翻到最底下有点麻烦)
优化设置入口(目前要点进自己主页才行，可以改成首页时从左侧边缘划出)

有一说一，感觉功能挺完善的，未来可期啊

**Comment by kagg886** [comment]
> 优化设置入口(目前要点进自己主页才行，可以改成首页时从左侧边缘划出)

~~是故意这么干的，我想如果我把设置写的好用的话那大概没有人会频繁地动设置.jpg~~
