### ISSUE TITLE
[FEATURE]希望除了能在设置中设置画廊列数，也能根据窗口宽度进行响应式设计

### ISSUE THREAD

**Issue by fr1g** [kagg886/Pixiv-MultiPlatform#2]
- [-] 我使用的是最新版的`Pixiv-MultiPlatform
- [-] 我保证在开发者回复issue时可以在第一时间知悉

# 1. 要添加/修改的功能

![QQ_1734286241517](https://github.com/user-attachments/assets/275e4522-cfbc-42d3-aea8-3b4f47398362)
thumbnail在高分辨率下体验会很奇怪，建议让用户可以选择使用根据窗口宽度的响应式布局

# 2. 要添加/修改的原因

因为默认状态下最大化窗口仍然还是3列实在是能清清楚楚看到每一个压缩后的颗粒！

**Comment by fr1g** [comment]
btw给头像放大一点然后切成圆形罢

**Comment by kagg886** [comment]
固定画廊列数和固定画廊列宽大概是不能同时进行的(悲

**Comment by fr1g** [comment]
可以让用户从这两个模式里选择发自我的 iPhone在 2024年12月16日，12:47，kagg886 ***@***.***> 写道：﻿
固定画廊列数和固定画廊列宽大概是不能同时进行的(悲

**Comment by kagg886** [comment]
现在有一个问题是如果要指定列宽的话那最小值和最大值分别怎么写emm(思考)

~~如果以窗口宽度为最大值的话可能会导致不必要的问题emm，现在的最新快照范围是写死的50-1000来着:D~~

**Comment by fr1g** [comment]
可以按px（发自我的 iPhone在 2024年12月17日，06:14，kagg886 ***@***.***> 写道：﻿
现在有一个问题是如果要指定列宽的话那最小值和最大值分别怎么写emm(思考)
如果以窗口宽度为最大值的话可能会导致不必要的问题emm，现在的最新快照范围是写死的50-1000来着:D

**Comment by kagg886** [comment]
目前按的就是px，其实我在想这个最小值和最大值该怎么配((
