### ISSUE TITLE
[FEATURE]希望在执行某些操作前有前端的二次确认

### ISSUE THREAD

**Issue by fr1g** [kagg886/Pixiv-MultiPlatform#3]
- [-] 我使用的是最新版的`Pixiv-MultiPlatform
- [-] 我保证在开发者回复issue时可以在第一时间知悉

# 1. 要添加/修改的功能

如题

# 2. 要添加/修改的原因

我真的只是好奇所以点了一下登出

**Comment by fr1g** [comment]
然后它就卡在“欢迎”和转圈圈了

**Comment by kagg886** [comment]
在最新快照中退出登录时会有登出提示
~~还有什么需要二次确认的地方吗.jpg~~
