### ISSUE TITLE
[FEATURE]希望增加私人收藏、小说字体相关功能

### ISSUE THREAD

**Issue by KTG-suger** [kagg886/Pixiv-MultiPlatform#5]
- [ - ] 我使用的是最新版的`Pixiv-MultiPlatform
- [ - ] 我保证在开发者回复issue时可以在第一时间知悉

# 1. 希望增加私人收藏、小说字体相关功能

> **在收藏时可以选择公开收藏/私人收藏/按标签收藏等（比如长按收藏进收藏选项，点按收藏默认收藏），增加默认收藏位置设置，同时在收藏页面也相对应的分开展示公开收藏与私人收藏。
另外个人感觉小说阅读的默认格式字体显得有一些小了，希望默认能大一点或者能够自己调节。**

# 2. 要添加/修改的原因

> **主要是我平时收藏大多都进私人收藏了，用了app以后一下子找不到自己收藏的图片小说都去哪了，一个个私人转公开麻烦先不说，得把xp公开给那些基友啊T_T。
开了自动排版以后字体明显感觉小了一号，不知道其他人有没有同样的感受，半夜躺着看小说确实不是很舒服。**

**Comment by kagg886** [comment]
涩涩必须！公开分享！
![05366420](https://github.com/user-attachments/assets/4529ed33-ded1-4627-bbee-c3de85e8d9de)
![05364A2F](https://github.com/user-attachments/assets/48983fee-1e42-47df-8cee-74c0d30dd146)
![05366420](https://github.com/user-attachments/assets/4529ed33-ded1-4627-bbee-c3de85e8d9de)

**Comment by KTG-suger** [comment]
> 涩涩必须！公开分享！ ![05366420](https://private-user-images.githubusercontent.com/68730049/397899754-4529ed33-ded1-4627-bbee-c3de85e8d9de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NTU2OTIsIm5iZiI6MTczNDc1NTM5MiwicGF0aCI6Ii82ODczMDA0OS8zOTc4OTk3NTQtNDUyOWVkMzMtZGVkMS00NjI3LWJiZWUtYzNkZTg1ZThkOWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDA0Mjk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NzMxOTk4M2UxYTBkYjM0NWU4NDJhNjJiNWExZjlmODFkNTUyMThkMjAwOTZlNTU3NmEwZmFlNTczMTY0ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Kbpp0zgIxWtRciu_cVkOVsfWrNmNUActlTNBWZrDFTE) ![05364A2F](https://private-user-images.githubusercontent.com/68730049/397899744-48983fee-1e42-47df-8cee-74c0d30dd146.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NTU2OTIsIm5iZiI6MTczNDc1NTM5MiwicGF0aCI6Ii82ODczMDA0OS8zOTc4OTk3NDQtNDg5ODNmZWUtMWU0Mi00N2RmLThjZWUtNzRjMGQzMGRkMTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDA0Mjk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNzU4ZTg1YmZkNzQ1ZWJiODc5NmFhZjExNGNmODVkN2FkNWIwMjM5MjJmMDVkYjg1ODIyYTVlNTQzN2E1YTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.g_zx-5VxS3oeOhcR_iKPhXkqEf9IJodQREihzNWdJcU) ![05366420](https://private-user-images.githubusercontent.com/68730049/397899754-4529ed33-ded1-4627-bbee-c3de85e8d9de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NTU2OTIsIm5iZiI6MTczNDc1NTM5MiwicGF0aCI6Ii82ODczMDA0OS8zOTc4OTk3NTQtNDUyOWVkMzMtZGVkMS00NjI3LWJiZWUtYzNkZTg1ZThkOWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDA0Mjk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NzMxOTk4M2UxYTBkYjM0NWU4NDJhNjJiNWExZjlmODFkNTUyMThkMjAwOTZlNTU3NmEwZmFlNTczMTY0ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Kbpp0zgIxWtRciu_cVkOVsfWrNmNUActlTNBWZrDFTE)

达咩达咩，人家会害羞的。

顺带说一下昨天我看小说时候，发现看作者分好的系列很麻烦，如果是最近更新的还好一下就翻到了，但是那种更新了好多的翻起来就很麻烦了，您看能不能给小说再加个系列查看。

**Comment by kagg886** [comment]
小说系列的epub导出建议单开一个issue，我想把它放到下个版本发布
本issue计划在查看私人收藏更新后即关闭然后发版QAQ

**Comment by KTG-suger** [comment]
> 小说系列的epub导出建议单开一个issue，我想把它放到下个版本发布 本issue计划在查看私人收藏更新后即关闭然后发版QAQ

ok，等我看两天小说到时候把有啥体验感觉要改的一起发。

**Comment by kagg886** [comment]
那我等下下个版本把查看资料给拆了全放到侧边栏里吧(

~~这玩意直接复用的查看别人空间主页的代码~~
